replicaCount: 2

image:
  repository: "us-central1-docker.pkg.dev/terraform-project-alemi-oct24/artemis/artemis"
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.0.0"

service:
  type: ClusterIP
  port: 5000
